# To work correctly, resulting APK file should have following files:
# * classes.dex — it should contain compiled code for both ebiten-generated
#                 bindings & code from src directory.
# * lib/*/libgojni.so — required by ebiten.
#
# To achieve that, we first create AAR using `ebitenmobile bind`, then unpack
# it as ordinary ZIP archive to access JAR with generated Java code and
# required *.so files.
#
# Then we compile Java code from `src` directory and convert it to DEX format
# along with JAR acquired from previous step.
#
# Then we pack everything into APK making sure that JNI `*.so` files are stored
# in `lib/<architecture>` directories.

# Android SDK & NDK environment settings. Modify according to SDK & NDK version
# installed in your system.
ANDROID_SDK_VERSION=28.0.3
ANDROID_SDK_PATH=/opt/android-sdk
ANDROID_NDK_PATH=/opt/android-ndk
ANDROID_JAR_VERSION=29

# Target package name.
ANDROID_PACKAGE=io.reconquest.app

# Settings for keystore which is used to sign APK.
KEYS_DN=DC=io,CN=reconquest
KEYS_PASS=123456
KEYS_VALIDITY=365
KEYS_ALGORITHM=RSA
KEYS_SIZE=2048

# Target build dir. Resulting APK file will be available here.
BUILD_DIR=build

_BUILD_TOOLS=$(ANDROID_SDK_PATH)/build-tools/$(ANDROID_SDK_VERSION)
_ANDROID_JAR_PATH=$(ANDROID_SDK_PATH)/platforms/android-$(ANDROID_JAR_VERSION)/android.jar
_JAVA_SRC=$(shell find src -name '*.java')

run: install
	adb shell am start -n $(ANDROID_PACKAGE)/.MainActivity

install: $(BUILD_DIR)/app.apk
	adb install $(BUILD_DIR)/app.apk

# Initialize keystore to sign APK.
keys.store:
	keytool -genkeypair \
		-validity $(KEYS_VALIDITY) \
		-keystore $@ \
		-keyalg $(KEYS_ALGORITHM) \
		-keysize $(KEYS_SIZE) \
		-storepass $(KEYS_PASS) \
		-keypass $(KEYS_PASS) \
		-dname $(KEYS_DN) \
		-deststoretype pkcs12

# Build AAR using ebitenmobile. This target is used to compile Go-code.
$(BUILD_DIR)/app.aar:
	@mkdir -p $(BUILD_DIR)

	GO111MODULE=off ANDROID_NDK_HOME=$(ANDROID_NDK_PATH) ebitenmobile bind \
		-target android \
		-javapkg $(ANDROID_PACKAGE) \
		-o $(BUILD_DIR)/app.aar \
		github.com/seletskiy/ebiten-android-minimal

	# Unpack resulting AAR library to link it to APK during further stages.
	@unzip -o -qq $(BUILD_DIR)/app.aar -d $(BUILD_DIR)/aar
	@ln -sf aar/jni $(BUILD_DIR)/lib

# Collect resources and generate R.java.
resources:
	$(_BUILD_TOOLS)/aapt package \
		-f \
		-m \
		-J src \
		-M AndroidManifest.xml \
		-S res \
		-I $(_ANDROID_JAR_PATH)

# Compile Java code. This target will reference classes generated by
# ebitenmobile.
compile: $(BUILD_DIR)/app.aar
	@mkdir -p $(BUILD_DIR)/obj

	javac \
		-d $(BUILD_DIR)/obj \
		-classpath src:$(BUILD_DIR)/aar/classes.jar \
		-bootclasspath $(_ANDROID_JAR_PATH) \
		$(_JAVA_SRC)

# Convert compiled Java code into DEX file (required by Android).
dex:
	$(_BUILD_TOOLS)/dx \
		--dex \
		--output $(BUILD_DIR)/classes.dex \
		$(BUILD_DIR)/obj \
		$(BUILD_DIR)/aar/classes.jar

# Package everything into unaligned APK file.
$(BUILD_DIR)/app.apk.unaligned: $(BUILD_DIR)/app.aar resources compile dex
	$(_BUILD_TOOLS)/aapt package \
		-f \
		-m \
		-F $(BUILD_DIR)/app.apk.unaligned \
		-M AndroidManifest.xml \
		-S res \
		-I $(_ANDROID_JAR_PATH)

	cd $(BUILD_DIR) && $(_BUILD_TOOLS)/aapt add \
		app.apk.unaligned \
		classes.dex \
		lib/*/*

# Align unaligned APK file and sign it using keystore.
$(BUILD_DIR)/app.apk: keys.store $(BUILD_DIR)/app.apk.unaligned
	$(_BUILD_TOOLS)/zipalign \
		-f 4 \
		$(BUILD_DIR)/app.apk.unaligned \
		$(BUILD_DIR)/app.apk

	$(_BUILD_TOOLS)/apksigner sign \
		--ks keys.store \
		--ks-pass pass:$(KEYS_PASS) \
		$(BUILD_DIR)/app.apk

clean:
	@rm -rf $(BUILD_DIR)
